export const  MDisplayB=[
    {id:1,
      src:"assets/Mobile-assets/mDisplay/mDisplayB1.png",
      alt:"b1"
    },
    {id:2,
      src:"assets/Mobile-assets/mDisplay/mDisplayB2.png",
      alt:"b2"
    },
    {id:3,
      src:"assets/Mobile-assets/mDisplay/mDisplayB3.png",
      alt:"b3"
    },
    {id:4,
      src:"assets/Mobile-assets/mDisplay/mDisplayB1.png",
      alt:"b1"
    },
    {id:5,
      src:"assets/Mobile-assets/mDisplay/mDisplayB2.png",
      alt:"b2"
    },
    {id:6,
      src:"assets/Mobile-assets/mDisplay/mDisplayB3.png",
      alt:"b3"
    },
    {id:7,
      src:"assets/Mobile-assets/mDisplay/mDisplayB1.png",
      alt:"b1"
    },
    {
        id:8,
      src:"assets/Mobile-assets/mDisplay/mDisplayB2.png",
      alt:"b2"
    },
    {id:9,
      src:"assets/Mobile-assets/mDisplay/mDisplayB3.png",
      alt:"b3"
    }
  ]