export const KidsB=[
  { "id": 1, "name": "Boys T-Shirt", "src": "assets/fashion/kids/Boys T-Shirt.jpg", "price": 499 },
  { "id": 2, "name": "Boys Jeans", "src": "assets/fashion/kids/Boys Jeans.jpg", "price": 899 },
  { "id": 3, "name": "Boys Shirt", "src": "assets/fashion/kids/Boys Shirt.jpg", "price": 799 },
  { "id": 4, "name": "Boys Shorts", "src": "assets/fashion/kids/Boys Shorts.jpg", "price": 699 },
  { "id": 5, "name": "Boys Jacket", "src": "assets/fashion/kids/Boys Jacket.jpg", "price": 1199 },
  { "id": 6, "name": "Boys Hoodie", "src": "assets/fashion/kids/Boys Hoodie.jpg", "price": 1099 },
  { "id": 7, "name": "Boys Tracksuit", "src": "assets/fashion/kids/Boys Tracksuit.jpg", "price": 1399 },
  { "id": 8, "name": "Boys Pajamas", "src": "assets/fashion/kids/Boys Pajamas.jpg", "price": 699 },
  { "id": 9, "name": "Boys Kurta Pyjama", "src": "assets/fashion/kids/Boys Kurta Pyjama.jpg", "price": 1299 },
  { "id": 10, "name": "Boys Sweater", "src": "assets/fashion/kids/Boys Sweater.jpg", "price": 999 },
  { "id": 11, "name": "Boys Blazer", "src": "assets/fashion/kids/Boys Blazer.jpg", "price": 1499 },
  { "id": 12, "name": "Boys Dungaree", "src": "assets/fashion/kids/Boys Dungaree.jpg", "price": 999 },
  { "id": 13, "name": "Boys Cap", "src": "assets/fashion/kids/Boys Cap.jpg", "price": 299 },
  { "id": 14, "name": "Boys Shoes", "src": "assets/fashion/kids/Boys Shoes.jpg", "price": 1499 },
  { "id": 15, "name": "Boys Sandals", "src": "assets/fashion/kids/Boys Sandals.jpg", "price": 999 },
  { "id": 16, "name": "Boys Socks", "src": "assets/fashion/kids/Boys Socks.jpg", "price": 199 },
    { "id": 17, "name": "Girls T-Shirt", "src": "assets/fashion/kids/Girls T-Shirt.jpg", "price": 499 },
  { "id": 18, "name": "Girls Jeans", "src": "assets/fashion/kids/Girls Jeans.jpg", "price": 899 },
  { "id": 19, "name": "Girls Frock", "src": "assets/fashion/kids/Girls Frock.jpg", "price": 999 },
  { "id": 20, "name": "Girls Skirt", "src": "assets/fashion/kids/Girls Skirt.jpg", "price": 799 },
  { "id": 21, "name": "Girls Jacket", "src": "assets/fashion/kids/Girls Jacket.jpg", "price": 1199 },
  { "id": 22, "name": "Girls Hoodie", "src": "assets/fashion/kids/Girls Hoodie.jpg", "price": 1099 },
  { "id": 23, "name": "Girls Tracksuit", "src": "assets/fashion/kids/Girls Tracksuit.jpg", "price": 1399 },
  { "id": 24, "name": "Girls Pajamas", "src": "assets/fashion/kids/Girls Pajamas.jpg", "price": 699 },
  { "id": 25, "name": "Girls Lehenga", "src": "assets/fashion/kids/Girls Lehenga.jpg", "price": 1499 },
  { "id": 26, "name": "Girls Sweater", "src": "assets/fashion/kids/Girls Sweater.jpg", "price": 999 },
  { "id": 27, "name": "Girls Blazer", "src": "assets/fashion/kids/Girls Blazer.jpg", "price": 1499 },
  { "id": 28, "name": "Girls Dungaree", "src": "assets/fashion/kids/Girls Dungaree.jpg", "price": 999 },
  { "id": 29, "name": "Girls Cap", "src": "assets/fashion/kids/Girls Cap.jpg", "price": 299 },
  { "id": 30, "name": "Girls Shoes", "src": "assets/fashion/kids/Girls Shoes.jpg", "price": 1499 },
  { "id": 31, "name": "Girls Sandals", "src": "assets/fashion/kids/Girls Sandals.jpg", "price": 999 },
  { "id": 32, "name": "Girls Socks", "src": "assets/fashion/kids/Girls Socks.jpg", "price": 199 }
]
