export const Products = [
  {
    id: 1,
    iphone16: [
      { pid: 101, model: "iPhone 16", specs: "128GB UltraMine", price: 67900, fullSpecs: {
        display: '6.1-inch OLED',
        processor: 'A18 Bionic chip',
        ram: '8 GB',
        storage: '128 GB / 256 GB / 512 GB / 1 TB',
        rearCamera: '48MP + 12MP Ultra Wide',
        frontCamera: '12MP TrueDepth',
        battery: 'Up to 28 hours video playback',
        os: 'iOS 18',
        waterResistance: 'IP68',
        faceID: 'Yes',
        support5G: 'Yes',
        magSafe: 'Yes',
        body: 'Titanium',
        weight: '206 grams',
        colors: 'Black, Silver, UltraMine, Natural'
      },src:"assets/Mobile-assets/mobiles/apple/iPhone16.jpg"},
      { pid: 102, model: "iPhone 16 Plus", specs: "256GB, white", price: 77999,fullSpecs: {
    "display": "6.7 inch OLED, 2778 x 1284 pixels",
    "processor": "Apple A18 Bionic",
    "storage": "256GB",
    "rearCamera": "Dual 48MP + 12MP",
    "frontCamera": "12MP TrueDepth",
    "battery": "4352 mAh",
    "charging": "20W fast charging, MagSafe wireless charging",
    "os": "iOS 18",
    "build": "Ceramic Shield front, Glass back, Aluminum frame",
    "waterResistance": "IP68 dust/water resistant (up to 6m for 30 mins)",
    "security": "Face ID",
    "connectivity": "5G, Wi‑Fi 6E, Bluetooth 5.3, NFC",
    "audio": "Stereo speakers, no headphone jack",
    "colors": "Midnight, Starlight, Red, Blue, Purple",
    "weight": "203 grams",
    "dimensions": "160.8 x 78.1 x 7.8 mm",
    "sim": "Dual SIM (nano‑SIM and eSIM)"
  },src:"assets/Mobile-assets/mobiles/apple/iphone16plus.jpg " },
      { pid: 103, model: "iPhone 16 Pro", specs: "256GB, Natural Titanium", price: 112900,fullSpecs: {
  "display": "6.1 inch LTPO Super Retina XDR OLED, 2796 x 1290 pixels, 120Hz ProMotion",
  "processor": "Apple A18 Pro",
  "storage": "512GB",
  "rearCamera": "Triple 48MP (Main) + 12MP (Ultra-Wide) + 12MP (5x Telephoto)",
  "frontCamera": "12MP TrueDepth with autofocus",
  "battery": "4441 mAh",
  "charging": "30W wired, MagSafe and Qi2 wireless charging",
  "os": "iOS 18",
  "build": "Titanium frame, Ceramic Shield front, Textured matte glass back",
  "waterResistance": "IP68 (up to 6 meters for 30 minutes)",
  "security": "Face ID",
  "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.3, NFC, USB-C",
  "audio": "Spatial Audio, Stereo speakers, No headphone jack",
  "colors": "Natural Titanium, Desert Titanium, Black Titanium, White Titanium",
  "weight": "221 grams",
  "dimensions": "159.9 x 76.7 x 8.25 mm",
  "sim": "Dual SIM (nano‑SIM and eSIM)"
},src:"assets/Mobile-assets/mobiles/apple/iphone 16 pro.png" },
      { pid: 104, model: "iPhone 16 Pro Max", specs: "512, Desert Titanium", price: 135900,fullSpecs: {
  "display": "6.7 inch LTPO Super Retina XDR OLED, 2796 x 1290 pixels, 120Hz ProMotion",
  "processor": "Apple A18 Pro",
  "storage": "512GB",
  "rearCamera": "Triple 48MP (Main) + 12MP (Ultra-Wide) + 12MP (5x Telephoto)",
  "frontCamera": "12MP TrueDepth with autofocus",
  "battery": "4441 mAh",
  "charging": "30W wired, MagSafe and Qi2 wireless charging",
  "os": "iOS 18",
  "build": "Titanium frame, Ceramic Shield front, Textured matte glass back",
  "waterResistance": "IP68 (up to 6 meters for 30 minutes)",
  "security": "Face ID",
  "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.3, NFC, USB-C",
  "audio": "Spatial Audio, Stereo speakers, No headphone jack",
  "colors": "Natural Titanium, Desert Titanium, Black Titanium, White Titanium",
  "weight": "221 grams",
  "dimensions": "159.9 x 76.7 x 8.25 mm",
  "sim": "Dual SIM (nano‑SIM and eSIM)"
},src:"assets/Mobile-assets/mobiles/apple/iphone 16 pro.png"}
    ]
  },
  {
    id: 2,
    samsungGalaxyS25: [
      { pid: 201, model: "Galaxy S25", specs: "8GB RAM, 128GB", price: 74999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/samsung/SamsungG S25.png"},
      { pid: 202, model: "Galaxy S25+", specs: "12GB RAM, 256GB", price: 89999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/samsung/SamsungG S25.png" },
      { pid: 203, model: "Galaxy S25 Ultra", specs: "16GB RAM, 512GB", price: 119999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/samsung/SamsungG S25.png" },
      { pid: 204, model: "Galaxy S25 FE", specs: "6GB RAM, 128GB", price: 64999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/samsung/SamsungG S25.png" }
    ]
  },
  {
    id: 3,
    oneplus: [
      { pid: 301, model: "OnePlus 13", specs: "8GB RAM, 128GB", price: 79999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/OnePlus/OnePlus 13.jpg" },
      { pid: 302, model: "OnePlus 13R", specs: "12GB RAM, 256GB", price: 43999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/OnePlus/OnePlus 13r.jpg" },
      { pid: 303, model: "OnePlus 12 ", specs: "16GB RAM, 512GB", price: 51422,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/OnePlus/OnePlus 12.jpg"},
      { pid: 304, model: "OnePlus 13 Lite", specs: "6GB RAM, 128GB", price: 58999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/OnePlus/OnePlus 12r.jpg" }
    ]
  },
  {
    id: 4,
    macbook: [
      { pid: 401, model: "MacBook Air Apple M4", specs: "8GB RAM, 256GB SSD", price: 99900,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
}, src:"assets/Mobile-assets/mobiles/macbook/Macbook Air M4.png" },
      { pid: 402, model: "MacBook Air Apple M2", specs: "16GB RAM, 512GB SSD", price: 82990,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
}, src:"assets/Mobile-assets/mobiles/macbook/Macbook Air M4.png" },
      { pid: 403, model: "MacBook Air Apple M1", specs: "8GB RAM, 256GB SSD", price: 59990,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
}, src:"assets/Mobile-assets/mobiles/macbook/Macbook Air M4.png" },
      { pid: 404, model: "MacBook Air Apple M3 ", specs: "8GB RAM, 512GB SSD", price: 97990,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
}, src:"assets/Mobile-assets/mobiles/macbook/Macbook Air M4.png" }
    ]
  },
  {
    id: 5,
    ipad: [
      { pid: 501, model: "iPad Mini", specs: "64GB, WiFi", price: 47999 ,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/iPad/iPad Mini.png" },
      { pid: 502, model: "iPad Air(M3)", specs: "256GB, WiFi + 5G", price: 104900,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/iPad/iPad Air (M3).jpg" },
      { pid: 503, model: "iPad Air(m3)", specs: "64GB, Space Grey wifi Only", price: 79999, fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/iPad/iPad Air (M3).jpg"},
      { pid: 504, model: "iPad Air(M2)", specs: "256GB, Silver Wifi +5G", price: 91900,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/iPad/iPad Air (M3).jpg" }
    ]
  },
  {
    id: 6,
    sonyXperia: [
      { pid: 601, model: "Sony Xperia XA1", specs: "4GB RAM, 328GB", price: 19999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Sony/sony-xperia-xa1.jpg" },
      { pid: 602, model: "Sony Xperia XZ", specs: "4GB RAM, 128GB", price: 49990,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Sony/sony-xperia-xz.jpg" },
      { pid: 603, model: "Sony Xperia XZ2", specs: "6GB RAM, 64GB", price: 74999 ,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Sony/sony-xperia-xz2.jpg"},
      { pid: 604, model: "Sony Xperia Pro", specs: "4GB RAM, 64GB", price: 29999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Sony/sony-xperia-xzs.jpg" }
    ]
  },
  {
    id: 7,
    googlePixel: [
      { pid: 701, model: "Google Pixel 7a", specs: "128GB, Coral", price: 43999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/google Pixel/pixel 7a.jpg" },
      { pid: 702, model: "Google Pixel 7", specs: "256GB, Cloudy White", price: 29999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/google Pixel/pixel7.jpg"  },
      { pid: 703, model: "Google Pixel 8", specs: "256GB, Wintergreen", price:75999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/google Pixel/pixel8.jpg" },
      { pid: 704, model: "Google Pixel 9", specs: "128GB, Hazle", price: 74999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/google Pixel/pixel-9.jpg" }
    ]
  },
  {
    id: 8,
    Realme: [
      { pid: 801, model: "realme 14 Pro+5G", specs: "8GB RAM, 128GB Pearl white" , price: 31999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Realme/realme 14Pro.jpg" },
      { pid: 802, model: "realme 13 pro+5G", specs: "8GB RAM, 256GB Monet", price: 26999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Realme/realme 13.jpg" },
      { pid: 803, model: "realme 14 x 5G", specs: "6GB RAM, 128GB Jewel Red", price: 14999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Realme/realme14.jpg" },
      { pid: 804, model: "realme P3", specs: "8GB RAM, 128GB", price: 19999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Realme/realme p3.jpg" },
      {
        pid:805, model:"realme C75",specs:"4GB Ram 128GB Lily White",price:12999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/Realme/realme c75.jpg"
      }
    ]
  },
  {
    id: 9,
    IQOO: [
      { pid: 901, model: "IQOO Neo 10R 5G", specs: "12GB RAM, 256GB MoonKnight Titan", price: 35999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/IQOO/neo-10r.jpg"},
      { pid: 902, model: "IQOO Z9 Lite 5G", specs: "4GB RAM, 128GB Mocha Brown", price: 14499,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
}, src:"assets/Mobile-assets/mobiles/IQOO/iQOO-z9-lite.jpg" },
      { pid: 903, model: "IQOO 13 5G", specs: "12GB RAM, 256GB Legend", price: 61999,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/IQOO/iqoo-13-5g.jpg" },
      { pid: 904, model: "IQOO Z10X 5G", specs: "8GB RAM, 256GB Titanium", price: 19999 ,fullSpecs: {
  display: '6.8 inch Dynamic AMOLED 2X, 120Hz',
  processor: ' Snapdragon 8 Gen 4 ',
  ram: '8GB',
  storage: '128GB / 256GB',
  rearCamera: '50MP (Wide) + 12MP (Ultra-Wide) + 10MP (Telephoto)',
  frontCamera: '12MP',
  battery: '4700 mAh',
  charging: '45W wired, 15W wireless',
  os: 'Android 15 with One UI 7',
  connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3',
  build: 'IP68 water and dust resistance',
  security: 'Ultrasonic Fingerprint Sensor, Face Recognition',
  weight: '195g',
  colors: 'Phantom Black, Cream, Green, Lavender'
},src:"assets/Mobile-assets/mobiles/IQOO/iqoo-z10x-5g.jpg"}
    ]
  }
 
];
